services:
  metric-app:
    build: ./container
    container_name: metric_checker
    privileged: true

    environment:
      - container=docker

    volumes:
      - ./data:/root/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    # extra_hosts:
    #   - "host.containers.internal:10.0.2.2"  # ✅ Podman-compatible

    network_mode: host

    stdin_open: true
    tty: true