services:
  metric-app:
    build: ./container
    container_name: metric_checker

    privileged: true

    environment:
      - container=docker
      - TZ=Asia/Kolkata

    volumes:
      - ./data:/root/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

    tmpfs:
      - /run
      - /run/lock
      - /tmp

    network_mode: host

    stdin_open: true
    tty: true