/tmp/metric_log.log {
  weekly
  rotate 4
  compress
  delaycompress
  missingok
  notifempty
  su root root
  postrotate
    /usr/local/bin/upload_logs.sh
  endscript
}

/tmp/server_alert_report.log {
  weekly
  rotate 4
  compress
  delaycompress
  missingok
  notifempty
  su root root
  postrotate
    /usr/local/bin/upload_logs.sh
  endscript
}